Update lfrc and lf preview

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -1,14 +1,15 @@
 # Required tools - lf:
-# 7z
-# ar
+# 7z (p7zip)
+# ar (binutils)
 # coreutils
 # dash
-# gunzip
+# gunzip (gzip)
 # tar
 # trash-cli
 # unrar
-# unxz
+# unxz (xz)
 # unzip
+# vidir (moreutils)
 # dragon-drop (optional) - https://github.com/mwh/dragon
 # fzf (optional)
 # hexedit (optional)
@@ -16,13 +17,13 @@
 # xclip (optional)
 #
 # Required tools - previewer:
-# 7z
-# ar
+# 7z (p7zip)
+# ar (binutils)
 # catdoc
-# convert
+# convert (imagemagick)
 # docx2txt
-# glow
-# gunzip
+# glow - https://github.com/charmbracelet/glow
+# gunzip (gzip)
 # mediainfo or exiftool
 # odt2txt
 # pdftotext
@@ -37,11 +38,11 @@
 # ueberzug (optional)
 
 # Basic settings
-set autoquit on
-set drawbox on
-set icons on
-set ignorecase on
-set preview on
+set noautoquit
+set drawbox
+set icons
+set ignorecase
+set preview
 set previewer ~/.config/lf/preview
 set cleaner ~/.config/lf/cleaner
 set scrolloff 4
@@ -62,25 +63,15 @@ cmd on-cd &{{
     esac
     printf "\033]0;$title - lf\007" > /dev/tty
 
-    # Reset prompt
-    fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%d\033[0m\033[1m%f\033[0m"
-    lf -remote "send $id set promptfmt \"$fmt\""
-
     # Show git branch in prompt
     set +e
-    branch=$(git branch --show-current 2> /dev/null)
-    [ -n "$branch" ] && lf -remote "send $id set promptfmt \"$fmt \033[33;1m $branch\033[0m\""
-}}
-
-cmd on-quit ${{
-    # Restore window title
-    #terminal=$(xprop -id $WINDOWID | grep '^WM_CLASS' | cut -d\" -f2)
-    #case "$terminal" in
-    #    st|st-*) title='st' ;;
-    #    xfce4-*) title='' ;;
-    #    *) title='Terminal' ;;
-    #esac
-    #printf "\033]0;$title\007" > /dev/tty
+    fmt="\033[32;1m%u@%h\033[0m:\033[34;1m%d\033[0m\033[1m%f\033[0m"
+    branch="$(git symbolic-ref --short HEAD 2>/dev/null)" || \
+    branch="tags/$(git describe --tags --exact-match HEAD 2>/dev/null)" || \
+    #branch="$(git describe --contains HEAD 2>/dev/null)" || \
+    branch="$(git name-rev --name-only --no-undefined --always HEAD 2>/dev/null)"
+    [ -n "$branch" ] && { lf -remote "send $id set promptfmt \"$fmt \033[33;1m $branch\033[0m\""; return; }
+    lf -remote "send $id set promptfmt \"$fmt\""
 }}
 
 cmd open ${{
@@ -228,29 +219,24 @@ cmd mkitem ${{
     s=$(printf '%s' "$f" | sed 's/\\/\\\\/g;s/"/\\"/g');
     if [ -e "$f" ]; then
         echo $cmd | grep -q "dir" && m="directory" || m="file"
-        m=$(printf "Cannot create %s '%s': File or directory exists!" "$m" "$s")
+        m=$(printf "Cannot create %s '%s': File or directory already exists!" "$m" "$s")
         lf -remote "send $id select \"$s\""
-        lf -remote "send $id echoerr \"$m\""
-        exit 0
-    fi
-    if [ ! -w "$PWD" ] && ! echo $cmd | grep -q "sudo"; then
-        echo $cmd | grep -q "dir" && m="directory" || m="file"
-        m=$(printf "Cannot create %s '%s': Permission denied!" "$m" "$s")
         lf -remote "send $id echoerr \"$m\""
         exit 0
     fi
     set +e
-    [ -n "${XDG_RUNTIME_DIR:-}" ] && tmpdir=$XDG_RUNTIME_DIR || tmpdir=${TMPDIR:-/tmp}
-    tmp="$(mktemp $tmpdir/lferror.XXXXXXXX)"
-    if $cmd -- $f 2> $tmp; then
-        lf -remote "send reload"
-        lf -remote "send $id select \"$s\""
-    else
-        lf -remote "send $id echoerr $(head -n 1 $tmp)"
-        cat $tmp
+    if ! error=$($cmd -- $f 2>&1); then
+        if printf '%s' "$error" | grep -q '[Pp]ermission denied'; then
+            echo $cmd | grep -q "dir" && m="directory" || m="file"
+            m=$(printf "Cannot create %s '%s': Permission denied!" "$m" "$s")
+        else
+            m=$(printf '%s' "$error" | head -n 1)
+        fi
+        lf -remote "send $id echoerr \"$m\""
+        exit 0
     fi
-    rm $tmp
-    set -e
+    lf -remote "send reload"
+    lf -remote "send $id select \"$s\""
 }}
 
 cmd chmod &{{
@@ -277,59 +263,28 @@ cmd chitem ${{
         exit 0
     fi
     set +e
-    [ -n "${XDG_RUNTIME_DIR:-}" ] && tmpdir=$XDG_RUNTIME_DIR || tmpdir=${TMPDIR:-/tmp}
-    tmp="$(mktemp $tmpdir/lferror.XXXXXXXX)"
-    if $cmd "$@" -- $fx 2> $tmp; then
-        lf -remote "send reload"
-        lf -remote "send $id unselect"
-        lf -remote "send $id echo Done"
-    else
-        lf -remote "send $id echoerr $(head -n 1 $tmp)"
-        cat $tmp
+    if ! error=$($cmd "$@" -- $fx 2>&1); then
+        lf -remote "send $id echoerr $(printf '%s' "$error" | head -n 1)"
+        exit 0
     fi
-    rm $tmp
-    set -e
+    lf -remote "send reload"
+    lf -remote "send $id unselect"
+    lf -remote "send $id echo Done"
 }}
 
 cmd bulkrename ${{
+    [ -z "$fx" ] && exit
     set -f
-    [ -n "${XDG_RUNTIME_DIR:-}" ] && tmpdir=$XDG_RUNTIME_DIR || tmpdir=${TMPDIR:-/tmp}
-    old="$(mktemp $tmpdir/lfbr.XXXXXXXX)"
-    new="$(mktemp $tmpdir/lfbr.XXXXXXXX)"
-    if [ -n "$fs" ]; then
-        files='' cwd=1
-        for f in $fs; do
-            fname=$(basename -- "$f")
-            fpath=$(dirname -- "$f")
-            files=$(printf '%s\n%s' "$files" "$fname")
-            [ "$fpath" != "$PWD" ] && cwd=0
-        done
-        [ $cwd -eq 1 ] && fs=${files#?}
-    else
-        set +f
-        for f in *; do
-            [ -e "$f" ] && fs=$(printf '%s\n%s' "$fs" "$f")
-        done
-        fs=$(printf '%s' "${fs#?}" | sort)
-        set -f
-    fi
-    printf '%s\n' "$fs" >"$old"
-    printf '%s\n' "$fs" >"$new"
-    $EDITOR "$new"
-    if [ "$(wc -l < "$new")" -ne "$(wc -l < "$old")" ]; then
-        rm -- "$old" "$new"
-        lf -remote "send $id echoerr Error: Number of lines must stay the same!"
-        exit 0
-    fi
-    paste "$old" "$new" | while IFS= read -r names; do
-        src="$(printf '%s' "$names" | cut -f1)"
-        dst="$(printf '%s' "$names" | cut -f2)"
-        if [ "$src" = "$dst" ] || [ ! -n "$dst" ] || [ -e "$dst" ]; then
-            continue
-        fi
-        mv -- "$src" "$dst"
+    files=''
+    cwd=$PWD
+    for f in $fx; do
+        fname=$(basename -- "$f")
+        fpath=$(dirname -- "$f")
+        files=$(printf '%s\n%s' "$files" "$fname")
+        [ "$fpath" != "$cwd" ] && cwd='' && break
     done
-    rm -- "$old" "$new"
+    [ -n "$cwd" ] && fx=${files#?}
+    printf '%s\n' "$fx" | vidir -
     lf -remote "send reload"
     lf -remote "send $id unselect"
 }}
@@ -372,23 +327,25 @@ cmd trash_restore ${{
 }}
 
 cmd fzf_jump ${{
+    header="Jump to location"
     if [ "$PWD" = "$HOME" ]; then
         if command -v fd >/dev/null; then
-            res="$(fd --max-depth=4 --follow -H -E .backups -E .cache -E .git -E .mozilla -E .thunderbird -E .windows | fzf --reverse --header='Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
+            res="$(fd --max-depth=4 --follow -H -E .backups -E .cache -E .git -E .mozilla -E .thunderbird -E .windows | fzf --reverse --header="$header")"
         else
-            res="$(find -L . -maxdepth 4 \(  -path './.backups' -o -path './.cache' -o -path '*/.git' -o -name '.gitignore' -o -path './.mozilla' -o -path './.thunderbird' -o -path './.windows' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header='Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
+            res="$(find -L . -maxdepth 4 \(  -path './.backups' -o -path './.cache' -o -path '*/.git' -o -name '.gitignore' -o -path './.mozilla' -o -path './.thunderbird' -o -path './.windows' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header="$header")"
         fi
     elif printf '%s' "$PWD" | grep -q $HOME; then
         if command -v fd >/dev/null; then
-            res="$(fd --follow -H -E .git | fzf --reverse --header='a Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
+            res="$(fd --follow -H -E .git | fzf --reverse --header="$header")"
         else
-            res="$(find -L . \( -path '*/.git' -o -name '.gitignore' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header='Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
+            res="$(find -L . \( -path '*/.git' -o -name '.gitignore' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header="$header")"
         fi
     else
-        res="$(find . -maxdepth 2 \( -path '*/.git' -o -name '.gitignore' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header='Jump to location' | sed 's/\\/\\\\/g;s/"/\\"/g')"
+        res="$(find . -maxdepth 2 \( -path '*/.git' -o -name '.gitignore' \) -prune -o -print 2> /dev/null | cut -b3- | fzf --reverse --header="$header")"
     fi
     [ -z "$res" ] && exit 0
-    [ -d "$res" ] && cmd="cd" || cmd="select"                                                       
+    [ -d "$res" ] && cmd="cd" || cmd="select"
+    res=$(printf '%s' "$res" | sed 's/\\/\\\\/g;s/"/\\"/g')
     lf -remote "send $id $cmd \"$res\""
 }}
 
@@ -438,6 +395,7 @@ cmd checksum &{{
 }}
 
 cmd checksums ${{
+    set -f
     printf '\nComputing %s checksums ...\n' "$2"
     for f in $fx; do
         [ "$PWD" = "$(dirname -- "$f")" ] && f=$(basename -- "$f")
@@ -459,13 +417,14 @@ cmd sha512sum sha512
 
 cmd unarchive-to &{{
     set -f
+    f=$(printf '%s' "$fx" | head -n 1)
     [ -d "$f" ] && exit 0
 
     f=$(basename -- "$f")
     case "$f" in
         *.tar.bz|*.tar.bz2|*.tar.gz|*.tar.xz|*.tar.zst)
             f=$(printf '%s' "$f" | sed -e 's/\.tar\.[[:alnum:]]\{2,3\}$//') ;;
-        *.7z|*.gz|*.xz|*.deb|*.iso|*.rar|*.tar|*.tbz|*.tbz2|*.tgz|*.txz|*.tzst|*.zip)
+        *.7z|*.gz|*.xz|*.deb|*.iso|*.jar|*.rar|*.tar|*.tbz|*.tbz2|*.tgz|*.txz|*.tzst|*.zip)
             f=$(printf '%s' "$f" | sed -e 's/\.[[:alnum:]]\{2,4\}$//') ;;
         *.AppImage|*.appimage)
             if [ ! -x "$f" ]; then
@@ -477,17 +436,18 @@ cmd unarchive-to &{{
             exit 0 ;;
     esac
     f=$(printf '%s' "$f" | sed -e "s/ /<space>/g")
-    lf -remote "send $id push :unarchive<space>current<space>file<space>into<space>directory:<space>$f"
+    lf -remote "send $id push :unarchive<space>selected<space>file<space>into<space>directory:<space>$f"
 }}
 
 cmd unarchive-here &{{
     set -f
+    f=$(printf '%s' "$fx" | head -n 1)
     [ -d "$f" ] && exit 0
 
     f=$(basename -- "$f")
     case "$f" in
         *.tar.bz|*.tar.bz2|*.tar.gz|*.tar.xz|*.tar.zst) ;;
-        *.7z|*.gz|*.xz|*.deb|*.iso|*.rar|*.tar|*.tbz|*.tbz2|*.tgz|*.txz|*.tzst|*.zip) ;;
+        *.7z|*.gz|*.xz|*.deb|*.iso|*.jar|*.rar|*.tar|*.tbz|*.tbz2|*.tgz|*.txz|*.tzst|*.zip) ;;
         *.AppImage|*.appimage)
             if [ ! -x "$f" ]; then
                 lf -remote "send $id echoerr AppImage is not executable : cannot extract files!"
@@ -496,11 +456,12 @@ cmd unarchive-here &{{
         *)  lf -remote "send $id echoerr Unsupported format!"
             exit 0 ;;
     esac
-    lf -remote "send $id push :unarchive<space>current<space>file<space>here?<space>[Y/n]<space>"
+    lf -remote "send $id push :unarchive<space>selected<space>file<space>here?<space>[Y/n]<space>"
 }}
 
 cmd unarchive ${{
     set -f
+    f=$(printf '%s' "$fx" | head -n 1)
     if [ $# -lt 4 ]; then
         lf -remote "send $id echo Aborted!"
         exit 0
@@ -519,7 +480,7 @@ cmd unarchive ${{
             *) mkdir -p -- $targetdir
         esac
     fi
-    oldfiles=$(ls --group-directories-first)
+    oldfiles=$(ls --group-directories-first -A)
     case "$f" in
         *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f -C $targetdir ;;
         *.tar.gz|*.tgz) tar xzvf $f -C $targetdir ;;
@@ -528,7 +489,7 @@ cmd unarchive ${{
         *.tar) tar xvf $f -C $targetdir ;;
         *.zip) unzip $f -d $targetdir ;;
         *.rar) unrar x $f $targetdir ;;
-        *.7z|*.iso) 7z x $f -o$targetdir ;;
+        *.7z|*.iso|*.jar) 7z x $f -o$targetdir ;;
         *.deb) cd -- $targetdir; ar xv $f; cd - >/dev/null ;;
         *.gz|*.xz)
             if [ "$targetdir" != "." ]; then
@@ -540,6 +501,7 @@ cmd unarchive ${{
                 *.gz) gunzip -- $f ;;
                 *) unxz -- $f ;;
             esac
+            [ "$targetdir" != "." ] && cd -
             ;;
         *.AppImage|*.appimage)
             if [ -e "squashfs-root" ]; then
@@ -562,7 +524,7 @@ cmd unarchive ${{
     else
         # Toggle extracted files and dirs and select the first item
         count=0
-        for n in $(ls --group-directories-first); do
+        for n in $(ls --group-directories-first -A); do
             for o in $oldfiles; do
                 [ "$n" = "$o" ] && break
             done
@@ -884,11 +846,10 @@ cmd acompress ${{
     read -r ans
 }}
 
-cmd dragon-all &dragon-drop -a -x $fx
-cmd dragon-stay &dragon-drop $fx
-cmd dragon-individual &dragon-drop -x $f
+cmd drag-once &dragon-drop -a -x $fx
+cmd drag-stay &dragon-drop $fx
 
-cmd dragon-receive ${{
+cmd drag-receive ${{
     set -f
     printf '\nWaiting url(s) or file(s) ...'
     set +e
@@ -985,6 +946,15 @@ cmd cd-media &{{
     done
 }}
 
+cmd open_or_up_open &{{
+    if [ -d "$f" ]; then
+        lf -remote "send $id open"
+    else
+        lf -remote "send $id up"
+        lf -remote "send $id open"
+    fi
+}}
+
 cmd ls !echo "\nls $(pwd | sed "s|$HOME|~|")";ls --color=auto --group-directories-first -alFh
 cmd sudolf $sudo -E lf
 cmd sudorm $sudo rm -r -i -- $fx
@@ -998,57 +968,65 @@ map J
 map K
 
 # Basic Functions
-map q :on-quit; quit
 map . set hidden!
-map R delete
+map * mark-remove
+map C clear
+map cc clear
+map cd push :cd<space>
+map cm push :chmod<space>
+map co push :chown<space>
+map csm push :sudochmod<space>
 map D trash_put
 map <a-d> trash_restore
 map <enter> open
-map C clear
-map U unselect
-map * mark-remove
-map cc clear
-map J push 5j
-map K push 5k
-map , find-next
-map ; find-prev
 map i $set -f; LESSOPEN='| ~/.config/lf/preview %s 0 0 0 0 verbose' less -R $f
-map I open-with sxiv
 map <a-m> mark-save
 map mm mark-save
 map md push :mkdir<space>
 map mf push :mkfile<space>
 map msd push :sudomkdir<space>
 map msf push :sudomkfile<space>
-map cd push :cd<space>
-map cm push :chmod<space>
-map co push :chown<space>
-map csm push :sudochmod<space>
+map <c-o> open-new-terminal
 map o push :open-with<space>
 map O push :open-with<space>pkexec<space>
 map P link
 map p paste-check
 map <a-p> paste
-map <c-o> open-new-terminal
-map <a-c> fzf_jump
+map <c-r> :on-cd; reload
+map R delete
+map T tag-toggle
+map U unselect
+
+# Applications
 map bc open-config
 map br bulkrename
 map e $set -f; if [ "$EDITOR" = "vim" ] || [ "$EDITOR" = "nvim" ]; then $EDITOR -p $fx; else $EDITOR $fx; fi
 map E sudoedit
 map <a-e> suedit
+map I open-with sxiv
+
+# Navigation
+map <a-c> fzf_jump
+map <a-j> :updir; down; open_or_up_open
+map <a-k> :updir; up; open
+map J push 5j
+map K push 5k
+map , find-next
+map ; find-prev
+
+# Preview and ratios
 map spd :set nopreview
-map spe :set preview on
+map spe :set preview
 map sr1 :set nopreview; set ratios 1
-map sr2 :set ratios 2:3; set preview on
-map sr3 :set ratios 1:2:3; set preview on
-map sr4 :set ratios 1:2:3:5; set preview on
-map T tag-toggle
-map ta dragon-all
-map ts dragon-stay
-map ti dragon-individual
-map tr dragon-receive
+map sr2 :set ratios 2:3; set preview
+map sr3 :set ratios 1:2:3; set preview
+map sr4 :set ratios 1:2:3:5; set preview
+
+# Drag and drop
+map to drag-once
+map ts drag-stay
+map tr drag-receive
 map td download-file
-map <c-r> :on-cd; reload
 
 # Archive Mappings
 map at compress tar
@@ -1079,3 +1057,12 @@ map g.l cd ~/.local
 map gtr cd ~/.local/share/Trash/files
 
 %[ $LF_LEVEL -eq 1 ] || echo "Warning: You're in a nested lf instance!"
+
+# Wait till lf server is up and running and update the prompt
+${{
+    preview="preview" && [ "$lf_preview" = "false" ] && preview="nopreview"
+    for i in 1 2 3 4 5 6 7 8 9 10; do
+        [ -z "$(lf -remote "send $id set $preview")" ] && break || sleep 0.2
+    done
+}}
+:on-cd
